### ISSUE TITLE
release 0.2.0

### ISSUE THREAD

**Issue by lukehinds** [sigstore/rekor#299]
Items needed for release 0.2.0

- [x] Implement RFC 3161 timestamp responses https://github.com/sigstore/rekor/pull/293
- [ ] Updated deployment documentation https://github.com/sigstore/rekor/issues/298
- [x] Decouple Trillian GRPC API from Rekor externals https://github.com/sigstore/rekor/pull/322
- [x] Add version flag https://github.com/sigstore/rekor/issues/303
- [x] Switch from api.rekor.dev to rekor.sigstore.dev #305 
- [ ] dog food signing and verification

**Comment by lukehinds** [comment]
correction, there is in fact already a 0.1.0, my bad (it was a while ago).

**Comment by cpanato** [comment]
same question here
@lukehinds @dlorenc @bobcallaway What is your plan date to release rekor 0.2.0? I would like to create the milestone to track the issues/prs and the planned date for the release.

I will create a milestone for now with no dates, but lets define a date

**Comment by lukehinds** [comment]
hey @cpanato , sorry for late reply. We might need to group up and think about the hard dates on releases. As it stands the main issue is we don't time box when patches will be completed by (in this case #282),  we just rely on the good will of someone to  pick up / complete the work.

tagging @dlorenc and @bobcallaway for thoughts.

**Comment by lukehinds** [comment]
https://github.com/sigstore/rekor/releases/tag/v0.2.0
